name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Push Package to Octopus Deploy
      # You may pin to the exact commit or the version.
      # uses: OctopusDeploy/push-package-action@b3ac5d3dd28d0ee9f3f06019eb325114d2f24a51
      uses: OctopusDeploy/push-package-action@v1.0.2
      with:
        # The API key used to access Octopus Deploy. You must provide an API key or username and password. If the guest account is enabled, a key of API-GUEST may be used. It is strongly recommended that this value retrieved from a GitHub secret.
        api_key: # optional
        # The path to a configuration file of default values with one "key=value" per line.
        config_file: # optional
        # Enable debug logging.
        debug: # optional, default is false
        # Ignore certificate errors when communicating with Octopus Deploy. Warning: enabling this option creates a security vulnerability.
        ignore_ssl_errors: # optional, default is false
        # The log level; valid options are "verbose", "debug", "information", "warning", "error", and "fatal".
        log_level: # optional, default is debug
        # Determines the action to perform with package if it already exists in the repository. Valid values are "FailIfExists", "OverwriteExisting", and "IgnoreIfExists".
        overwrite_mode: # optional, default is FailIfExists
        # A comma-delimited list of packages to push to Octopus Deploy (i.e. package1,package2).
        packages: # optional
        # The password to used to authenticate with Octopus Deploy. It is strongly recommended to retrieve this value from a GitHub secret.
        password: # optional
        # The URL of a proxy to use (i.e. https://proxy.example.com).
        proxy: # optional
        # The password used to connect to a proxy. It is strongly recommended to retrieve this value from a GitHub secret. If proxy_username and proxy_password are omitted and proxy URL is specified, the default credentials are used.
        proxy_password: # optional
        # The username used to connect to a proxy. It is strongly recommended to retrieve this value from a GitHub secret.
        proxy_username: # optional
        # If the package already exists in the repository, the default behavior is to reject the new package being pushed. You can pass this flag to overwrite the existing package. This flag may be deprecated in a future version; passing it is the same as using "OverwriteExisting" for the input, overwrite_mode.
        release_existing: # optional
        # The base URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). It is recommended to retrieve this value from an environment variable.
        server: # optional
        # The name or ID of a space within which this command will be executed. If omitted, the default space will be used.
        space: # optional
        # A timeout value in seconds for network operations.
        timeout: # optional, default is 600
        # Use delta compression when uploading packages to Octopus Deploy.
        use_delta_compression: # optional, default is true,
        # The username used to authenticate with Octopus Deploy. You must provide an apiKey or username and password. It is strongly recommended to retrieve this value from a GitHub secret.
        username: # optional
